[[intro]]
== Introduction

The http://georeferencing.org/georefcalculator/gc.html[Georeferencing Calculator^] (Wieczorek & Wieczorek 2019) described in this document is a tool created to aid in the [[georeference,georeferencing]] of descriptive localities such as those found in museum-based natural history collections. It was originally designed for the Mammal Networked Information System (MaNIS) and has been widely adopted in other large-scale collaborative georeferencing projects to supplement semi-automated georeferencing tools. The application makes calculations using the theory given in https://doi.org/10.15468/doc-gg7h-s853[Georeferencing Best Practices^] (Chapman & Wieczorek 2020), derived from the earlier http://georeferencing.org/georefcalculator/docs/GeorefGuide.html[MaNIS/HerpNET/ORNIS Georeferencing Guidelines^] (Wieczorek 2001), and https://doi.org/10.1080/13658810412331280211[The point-radius method for georeferencing locality descriptions and calculating associated uncertainty^] (Wieczorek et al. 2004). Specific methods for calculating a wide variety of examples of the distinct locality types are given in https://doi.org/10.35035/e09p-h128[Georeferencing Quick Reference Guide^] (Zermoglio et al. 2020).

Throughout this document there are terms in bold. These signify that there is a very specific meaning for the term as it is being used here, and these are defined in detail in the <<Glossary>> of Georeferencing Best Practices, some of which are included in the <<Glossary>> of this document as well, for convenience. Terms in italics and not bold (e.g. Input Latitude) are references to fields or their labels in the Calculator. Darwin Core terms are displayed in monospace (e.g., term:dwc[georeferenceRemarks]) in all GBIF digital documentation.
