[[intro]]
== Introduction

The http://georeferencing.org/georefcalculator/gc.html[Georeferencing Calculator (Wieczorek & Wieczorek 2020)^] described in this document is a tool created to aid in the <<georeference,georeferencing>> of descriptive <<locality,localities>> such as those found in museum-based natural history collections. It was originally designed for the Mammal Networked Information System (MaNIS) and has been widely adopted in other large-scale collaborative georeferencing projects to supplement semi-automated georeferencing tools. The application makes calculations using the theory given in {gbp}[Georeferencing Best Practices (Chapman & Wieczorek 2020)^], derived from the earlier http://georeferencing.org/georefcalculator/docs/GeorefGuide.html[MaNIS/HerpNET/ORNIS Georeferencing Guidelines (Wieczorek 2001)^], and https://doi.org/10.1080/13658810412331280211[The point-radius method for georeferencing locality descriptions and calculating associated uncertainty (Wieczorek et al. 2004)^]. Specific methods for calculating a wide variety of examples of the distinct locality types are given in {gqg}[Georeferencing Quick Reference Guide (Zermoglio et al. 2020)^].

Underlined terms throughout this document (e.g. <<accuracy>>) link to definitions in the <<Glossary>> (the same glossary of terms used in {gbp}[Georeferencing Best Practices^], while terms in italics (e.g. xref:ui-input-latitude[role=ui-element]) refer to fields and/or labels in the Calculator. <<darwin-core,Darwin Core>> terms are displayed in monospace (e.g. term:dwc[georeferenceRemarks]) in all GBIF digital documentation and link to the definitions maintained by Biodiversity Information Standards (TDWG) in the approved https://dwc.tdwg.org/list/[List of Darwin Core terms^].
