[[citation-and-documentation]]
== Citation and Documentation

Any time the *_Georeferencing Calculator_* is used, the *georeferencer* should record its use.

If the *Darwin Core* standard is used to record *_Calculator_* output, the *_Calculator_* version and the date of use should be recorded in the field term:[georeferenceSources]. The following format should be used:

====
Wieczorek C, J Wieczorek. Georeferencing Calculator. Version: [yyyymmdd(language)]. Available: http://georeferencing.org/georefcalculator/gc.html. Accessed [yyyy-mm-dd].
====

.{blank}
[caption="For example"]
====
Wieczorek C, J Wieczorek. Georeferencing Calculator. Version: 20191217en. Available: http://georeferencing.org/georefcalculator/gc.html. Accessed 2020-01-28.
====

The version and language of the *_Calculator_* can be found in the lower left-hand corner of the calculator.

If the *Darwin Core* standard is not used to record calculator output, the *georeferencer* should record this citation in a suitable field in the database of choice and in any written documentation or notes for future georeferencing efforts.
