https://docs.gbif.org/documentation-guidelines/[image:https://docs.gbif.org/documentation-guidelines/gbif-document-shield.svg[GBIF Document]]
https://doi.org/10.35035/gdwq-3v93[image:https://zenodo.org/badge/DOI/10.35035/gdwq-3v93.svg[doi:10.35035/gdwq-3v93]]
https://creativecommons.org/licenses/by-sa/4.0/[image:https://img.shields.io/badge/License-CC%20BY%2D-SA%204.0-lightgrey.svg[CC BY-SA 4.0]]
https://builds.gbif.org/job/doc-georeferencing-calculator-manual/lastBuild/console[image:https://builds.gbif.org/job/doc-georeferencing-calculator-manual/badge/icon[Build status]]
// CrowdIn badge:
https://crowdin.com/project/georef-calculator-manu[image:https://badges.crowdin.net/georef-calculator-manu/localized.svg[Translation progress]]

= Georeferencing Calculator Manual

_This is information *about* this document's source code.  It is not part of the document._

The document is available in a temporary location as HTML and PDF at https://docs.gbif.org/georeferencing-calculator-manual/1.0/en/[Georeferencing Calculator Manual].

The document is built using AsciiDoc, for guidance on how to make changes or suggestions see the https://docs.gbif.org/documentation-guidelines/[GBIF Documentation Guidelines].

== Special format for UI names

UI elements are listed in appendix A, using this syntax:

[source,asciidoc]
----
[[ui-calculate]]Calculate:: Button used to calculate…
----

They are referenced in the text using this syntax:

[source,asciidoc]
----
xref:ui-calculate[role=ui-element]
----

There's generally no need to override the link text, as the UI element names don't change.

UI elements without an entry in the appending can be formatted like this:

[source,asciidoc]
----
[ui-element]#OK#
----

== Notes for translators

The AsciiDoctor attributes `{gbp}` points to the English Georeferencing Best Practices Guide, to make links to this document easier.  `{gqg}` points to the Georeferencing Quick Reference Guide.  `{gbp-es}` and `{gqg-es}` point to the Spanish versions of these documents.  The attributes are defined in `index.en.adoc`.

Translations in progress can be viewed on the https://docs.gbif-uat.org/georeferencing-calculator-manual/[UAT site].
